services:
  cache-service:
    build:
      context: .
    container_name: cache-service
    restart: unless-stopped
    ports:
      - "${CACHE_PORT:-50051}:${CACHE_PORT:-50051}"
      - "${CACHE_HEALTH_PORT:-58080}:${CACHE_HEALTH_PORT:-58080}"
    environment:
      - CACHE_LOG_LEVEL=${CACHE_LOG_LEVEL:-INFO}
      - CACHE_PORT=${CACHE_PORT:-50051}
      - CACHE_HEALTH_HOST=${CACHE_HEALTH_HOST:-0.0.0.0}
      - CACHE_HEALTH_PORT=${CACHE_HEALTH_PORT:-58080}
